name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.8
      - run: bun install
      - run: bunx playwright install --with-deps
      - run: bun run build
      - run: bun run test
